//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_BSC.Trio.DAL.TrioDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int PlanID { get; set; }
        public bool Trio { get; set; }
        public bool SN { get; set; }
        public bool Full { get; set; }
        public int LocationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime LastUpdatedDT { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
