//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_BSC.Trio.DAL.TrioDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalManagementEntities : DbContext
    {
        public HospitalManagementEntities()
            : base("name=HospitalManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessUnit> BusinessUnits { get; set; }
        public virtual DbSet<CBSA> CBSAs { get; set; }
        public virtual DbSet<CollateralInfo> CollateralInfoes { get; set; }
        public virtual DbSet<CollateralType> CollateralTypes { get; set; }
        public virtual DbSet<GeoType> GeoTypes { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MapType> MapTypes { get; set; }
        public virtual DbSet<PCP> PCPs { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
